name       : python-outcome
version    : 1.1.0
release    : 1
source     :
    - https://github.com/python-trio/outcome/archive/v1.1.0.tar.gz : cc1dd2d80cec860d8dfd598626fd54b4f14684fee0dffade6d09d38fb01432bc
license    : Apache-2.0
component  : programming.python
summary    : Capture the outcome of Python function calls 
description: |
    Capture the outcome of Python function calls
builddeps  :
    - python-pytest
    - python-pytest-asyncio
rundeps    :
    - python-attrs
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
