name       : python-outcome
version    : 1.2.0
release    : 4
source     :
    - https://github.com/python-trio/outcome/archive/refs/tags/v1.2.0.tar.gz : 94605c5f4073b83dad69eb032d63f7ce31033b6d901f84b428a4b2a6a919ab4f
homepage   : https://github.com/python-trio/outcome
license    : Apache-2.0
component  : programming.python
summary    : Capture the outcome of Python function calls
description: |
    Capture the outcome of Python function calls. Extracted from the Trio project.
builddeps  :
    - python-pytest
    - python-pytest-asyncio
rundeps    :
    - python-attrs
build      : |
    %python3_setup
install    : |
    %python3_install
check      : |
    %python3_test pytest3
